In [1]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
# Pick up certain value by index

print(a[1,2])

6


In [36]:
# Extract sub-matrix 

# 1). from cross points of regular rows & columns specified by slice objects
print(a[0:3:2, 1:3:1])

# 2). from cross points of any rows & columns
print(a[np.ix_([0,2],[1,2,3])])

[[ 1  2]
 [ 9 10]]
[[ 1  2  3]
 [ 9 10 11]]


In [39]:
# Form a new Matrix with arbitrary dimensions
# The necessary indices of each dimension is specified by a list or np.array.
# The two indices is given to the orignal 2-dims matrix; three indices for 3-dims matrix

print(a[[1,2], [0,3]])

i = np.array( [ [0,1],                        # indices for the first dim of a
                [1,2] ] )
j = np.array( [ [2,1],                        # indices for the second dim
                [3,3] ] )
print(a[i,j])

[ 4 11]
[[ 2  5]
 [ 7 11]]


In [41]:
print(a[i,2])

[[ 2  6]
 [ 6 10]]


In [43]:
print(a[:,j])

[[[ 2  1]
  [ 3  3]]

 [[ 6  5]
  [ 7  7]]

 [[10  9]
  [11 11]]]
