In [1]:
import numpy as np

In [21]:
a = np.arange(20).reshape(5,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [22]:
# Pick up certain value by index

print(a[1,2])

6


In [62]:
# Extract sub-matrix in some rows and columns

###############################################################################
# NOTE: This is achieved by combining a scalar_value/slice_object with a list
#       Only ix_() function can accept two lists
###############################################################################

# 1). from cross points of regular rows & columns specified by slice objects
print(a[0:3:2, 1:3:1])  # each dim's indices is broadcast to fit each other
print()

print(a[[1,3,4]])
print()

# same as previous one
print(a[[1,3,4],:])     # ":" is broadcast to fit into [1,3,4]
print()

# same as previous one
print(a[[1,3,4]])
print()

print(a[:, [1,3]])     # ":" is broadcast to fit into [1,3]
print()

print(a[2, [1,3]])
print()

# 2). from cross points of any rows & columns
print(a[np.ix_([0,2],[1,2,3])])
print()


[[ 1  2]
 [ 9 10]]

[[ 4  5  6  7]
 [12 13 14 15]
 [16 17 18 19]]

[[ 4  5  6  7]
 [12 13 14 15]
 [16 17 18 19]]

[[ 4  5  6  7]
 [12 13 14 15]
 [16 17 18 19]]

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]

[ 9 11]

[[ 1  2  3]
 [ 9 10 11]]



In [60]:
# Form a new Matrix with arbitrary dimensions
# The necessary indices for each axis is specified by a list or np.array.
# The indices shape is the new Matrix shape.
# The two indices is given to the orignal 2-dims matrix; three indices for 3-dims matrix

######################################################################
# NOTE: This is achieved by combining two list/np.array objects
######################################################################

print(a[[1,2], [0,3]])
print()

print(a[ [ [0,1],                        # indices for the first dim of a
           [1,2] ],
         [ [2,1],                        # indices for the second dim
           [3,3] ] ])

i = np.array( [ [0,1],                        # indices for the first dim of a
                [1,2] ] )
j = np.array( [ [2,1],                        # indices for the second dim
                [3,3] ] )
print(a[i,j])
print()


[ 4 11]

[[ 2  5]
 [ 7 11]]
[[ 2  5]
 [ 7 11]]



In [13]:
# '2' will be broadcast to fit into 'i'

print(a[i,2])

print('----------------')

# '1:3:1' is broadcast to fit into 'j'

print(a[1:3:1,j])

print('----------------')

# Both ':' and 'j' are broadcast to fit each other

print(a[:,j])
 
print('----------------')

[[ 2  6]
 [ 6 10]]
----------------
[[[ 6  5]
  [ 7  7]]

 [[10  9]
  [11 11]]]
----------------
[[[ 2  1]
  [ 3  3]]

 [[ 6  5]
  [ 7  7]]

 [[10  9]
  [11 11]]]
----------------


In [1]:
# enumerate elements

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print()
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
