In [9]:
import numpy as np

a = np.arange(1,10)
print(a)
print(a.shape)
a.shape = (9,-1)
print(a.flags.owndata, a.base)
print(a)

b = np.arange(0,24)
print(b)
 ### (batches, rows, columns)
b.shape = (2,3,4)
print(b.flags.owndata, b.base)
print(b)

[1 2 3 4 5 6 7 8 9]
(9,)
True None
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
True None
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [2]:
# slicing : produce VIEW of array
a = np.arange(1,10)
b = a[:]
print(b.flags.owndata, b.base)
b[4] = 10
print(a)

False [1 2 3 4 5 6 7 8 9]
[ 1  2  3  4 10  6  7  8  9]


In [6]:
# reshape : VIEW
a = np.arange(1,10)
b = a.reshape((3,3))
print(b.flags.owndata, b.base)
a[4] = 10
print(b)
b[1,1] = 11
print(a)

False [1 2 3 4 5 6 7 8 9]
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
[ 1  2  3  4 11  6  7  8  9]


In [4]:
# ravel : VIEW
a = np.arange(1,10).reshape(3,3)
print(a.flags.owndata, a.base)
b = a.ravel()
print(b.flags.owndata, b.base)
b[4] = 10
print(a)
print(b)

False [1 2 3 4 5 6 7 8 9]
False [1 2 3 4 5 6 7 8 9]
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
[ 1  2  3  4 10  6  7  8  9]


In [7]:
# T (Transpose) : VIEW
a = np.arange(1,10)
aT = a.T
print(aT.flags.owndata, aT.base)
aTp = a.transpose()
print(aTp.flags.owndata, aTp.base)
aT[4] = 10
print(a)

False [1 2 3 4 5 6 7 8 9]
False [1 2 3 4 5 6 7 8 9]
[ 1  2  3  4 10  6  7  8  9]


In [6]:
# flatten : COPY
a = np.arange(1,10)
b = a.flatten()
print(b.flags.owndata, b.base)
b[4] = 10
print(a)

c = a.flat
print(repr(a), repr(c))

True None
[1 2 3 4 5 6 7 8 9]
array([1, 2, 3, 4, 5, 6, 7, 8, 9]) <numpy.flatiter object at 0x557a48e2c240>


In [7]:
# vstack : COPY
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
c = np.vstack((a,b))
print(c.flags.owndata, c.base)
a[1,1] = 10
b[1,1] = 20
print(a)
print(b)
print(c)

True None
[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
[[11 12 13]
 [14 20 16]
 [17 18 19]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [7]:
print("Force a copy so that diminish the confusion caused by whether it's a view or not!")
aT = np.array(a.T, copy=True)
print(aT.flags.owndata, aT.base)

Force a copy so that diminish the confusion caused by whether it's a view or not!
True None
